att: nodejs CI

diff --git a/.github/workflows/nodejs-ci.yaml b/.github/workflows/nodejs-ci.yaml
--- a/.github/workflows/nodejs-ci.yaml
+++ b/.github/workflows/nodejs-ci.yaml
@@ -30,3 +30,14 @@ jobs:
       env:
         SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
         SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
+        
+    - name: "Show SonarQube Quality Gate Status"
+      run: echo "The Quality Gate status is ${{ steps.sonarqube-quality-gate-check.outputs.quality-gate-status }}"
+
+    - name: "Fail if Quality Gate failed"
+      run: |
+        if [[ "${{ steps.sonarqube-quality-gate-check.outputs.quality-gate-status }}" != "PASSED" ]]; then
+          echo "Quality Gate has failed. Exiting."
+          exit 1
+        fi
+      
